apiVersion: v1
kind: Secret
metadata:
  name: neon-beat-prod-secrets
  namespace: neon-beat
  labels:
    app.kubernetes.io/name: neon-beat
    app.kubernetes.io/instance: prod
type: Opaque
stringData:
  COUCH_USERNAME: admin
  COUCH_PASSWORD: change-me
