apiVersion: v1
kind: Secret
metadata:
  name: neon-beat-preprod-secrets
  namespace: neon-beat-preprod
  labels:
    app.kubernetes.io/name: neon-beat
    app.kubernetes.io/instance: preprod
type: Opaque
stringData:
  COUCH_USERNAME: admin
  COUCH_PASSWORD: change-me
